version: '3.9'
services:
  redis_twitter:
    network_mode: host
    image: "redis:5.0.14"
    command: redis-server
    environment:
      - REDIS_REPLICATION_MODE=master
    profiles: [ 'testing' ]
  twitter_extractor:
    init: true
    network_mode: host
    restart: unless-stopped
    user: "${USER_ID}:${GROUP_ID}"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./docker_volume:/app/docker_volume
    profiles: ['production', 'testing']
  mongo_test:
    network_mode: host
    restart: unless-stopped
    command: mongod --port 30017
    image: "mongo:4.0.1"
    container_name: db
    volumes:
      - /data/db
    profiles: ['production', 'testing']
