version: '3'
services:
  twitter_extractor:
    init: true
    network_mode: host
    restart: unless-stopped
    user: "${USER_ID}:${GROUP_ID}"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./docker_volume:/app/docker_volume
  redis_twitter:
    network_mode: host
    restart: unless-stopped
    image: "redis:5.0.14"
    command: redis-server
    environment:
      - REDIS_REPLICATION_MODE=master
    profiles:
      - testing